In [9]:
import numpy as np

In [10]:
A = np.array([[3,4,3,1], [1,3,2,6], [2,4,1,5],[3,3,5,2]])
U, D, V = np.linalg.svd(A)
U


array([[-0.43124523,  0.49315012, -0.55075835, -0.51719991],
       [-0.53273754, -0.53052572,  0.41966021, -0.50854546],
       [-0.52374556, -0.40520071, -0.48729169,  0.5692537 ],
       [-0.50587435,  0.5578152 ,  0.53206894,  0.38708653]])

In [11]:
V

array([[-0.3593326 , -0.56750746, -0.4428526 , -0.59388293],
       [ 0.36767659,  0.08799758,  0.56862492, -0.73057242],
       [-0.29605046, -0.62845599,  0.65902357,  0.28824492],
       [ 0.80501437, -0.52462823, -0.21502376,  0.17459057]])

In [40]:
for row in V : 
    print(row) 
rez = [[V[j][i] for j in range(len(V))] for i in range(len(V[0]))] 
print("\n") 
for row in rez: 
    print(row) 


[-0.3593326  -0.56750746 -0.4428526  -0.59388293]
[ 0.36767659  0.08799758  0.56862492 -0.73057242]
[-0.29605046 -0.62845599  0.65902357  0.28824492]
[ 0.80501437 -0.52462823 -0.21502376  0.17459057]


[-0.35933259791154737, 0.3676765887075529, -0.29605045619593257, 0.8050143710398562]
[-0.5675074604972962, 0.08799758087108188, -0.6284559894201118, -0.5246282277982528]
[-0.4428526020082162, 0.568624915473525, 0.6590235660195086, -0.2150237610781874]
[-0.5938829339630837, -0.7305724176150787, 0.28824492394333495, 0.17459057015875665]


In [41]:
D

array([12.22151125,  4.92815942,  2.06380839,  0.29766152])

In [42]:
sigma = np.array([[12.22151125,0], [0,4.92815942]])

In [43]:
m = np.matrix(sigma)

In [44]:
inverseMatrix = np.linalg.inv(m)
inverseMatrix

matrix([[0.08182294, 0.        ],
        [0.        , 0.20291551]])

In [49]:
U=U[:, 0:2]

In [50]:
Alice = np.array([5,3,4,4])

In [51]:
intermidiate = np.matmul(Alice, U)

In [52]:
final = np.matmul(intermidiate,inverseMatrix)

In [53]:
final

matrix([[-0.64418534,  0.30125475]])